name: Pipeline CI Rusak

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run error command
        run: echo "Simulasi yang benar kembali"
